//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IgramaticaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class gramaticaBaseListener : IgramaticaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] gramaticaParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] gramaticaParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.lista_declaracion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLista_declaracion([NotNull] gramaticaParser.Lista_declaracionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.lista_declaracion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLista_declaracion([NotNull] gramaticaParser.Lista_declaracionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>declaracionVariable</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracionVariable([NotNull] gramaticaParser.DeclaracionVariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>declaracionVariable</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracionVariable([NotNull] gramaticaParser.DeclaracionVariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>declaracionFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_funcion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracionFuncion([NotNull] gramaticaParser.DeclaracionFuncionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>declaracionFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_funcion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracionFuncion([NotNull] gramaticaParser.DeclaracionFuncionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.lista_instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLista_instrucciones([NotNull] gramaticaParser.Lista_instruccionesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.lista_instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLista_instrucciones([NotNull] gramaticaParser.Lista_instruccionesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaAsignacion([NotNull] gramaticaParser.SentenciaAsignacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaAsignacion([NotNull] gramaticaParser.SentenciaAsignacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaIf</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaIf([NotNull] gramaticaParser.SentenciaIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaIf</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaIf([NotNull] gramaticaParser.SentenciaIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaFor</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaFor([NotNull] gramaticaParser.SentenciaForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaFor</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaFor([NotNull] gramaticaParser.SentenciaForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaSwitch</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaSwitch([NotNull] gramaticaParser.SentenciaSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaSwitch</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaSwitch([NotNull] gramaticaParser.SentenciaSwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaReturn</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaReturn([NotNull] gramaticaParser.SentenciaReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaReturn</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaReturn([NotNull] gramaticaParser.SentenciaReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>llamadaFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLlamadaFuncion([NotNull] gramaticaParser.LlamadaFuncionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>llamadaFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLlamadaFuncion([NotNull] gramaticaParser.LlamadaFuncionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaContinue</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaContinue([NotNull] gramaticaParser.SentenciaContinueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaContinue</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaContinue([NotNull] gramaticaParser.SentenciaContinueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaBrea</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaBrea([NotNull] gramaticaParser.SentenciaBreaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaBrea</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaBrea([NotNull] gramaticaParser.SentenciaBreaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>senteciaAux</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSenteciaAux([NotNull] gramaticaParser.SenteciaAuxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>senteciaAux</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSenteciaAux([NotNull] gramaticaParser.SenteciaAuxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsigacionconValor</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaAsigacionconValor([NotNull] gramaticaParser.SentenciaAsigacionconValorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsigacionconValor</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaAsigacionconValor([NotNull] gramaticaParser.SentenciaAsigacionconValorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsignacionComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaAsignacionComun([NotNull] gramaticaParser.SentenciaAsignacionComunContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsignacionComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaAsignacionComun([NotNull] gramaticaParser.SentenciaAsignacionComunContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaIncremento</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaIncremento([NotNull] gramaticaParser.SentenciaIncrementoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaIncremento</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaIncremento([NotNull] gramaticaParser.SentenciaIncrementoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsignacionSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaAsignacionSlice([NotNull] gramaticaParser.SentenciaAsignacionSliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsignacionSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaAsignacionSlice([NotNull] gramaticaParser.SentenciaAsignacionSliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentencia_if([NotNull] gramaticaParser.Sentencia_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentencia_if([NotNull] gramaticaParser.Sentencia_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloque_if([NotNull] gramaticaParser.Bloque_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloque_if([NotNull] gramaticaParser.Bloque_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_if_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloque_if_else([NotNull] gramaticaParser.Bloque_if_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_if_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloque_if_else([NotNull] gramaticaParser.Bloque_if_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloque_else([NotNull] gramaticaParser.Bloque_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloque_else([NotNull] gramaticaParser.Bloque_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaForComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaForComun([NotNull] gramaticaParser.SentenciaForComunContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaForComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaForComun([NotNull] gramaticaParser.SentenciaForComunContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaForEstiloGo</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentenciaForEstiloGo([NotNull] gramaticaParser.SentenciaForEstiloGoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaForEstiloGo</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentenciaForEstiloGo([NotNull] gramaticaParser.SentenciaForEstiloGoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_switch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentencia_switch([NotNull] gramaticaParser.Sentencia_switchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_switch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentencia_switch([NotNull] gramaticaParser.Sentencia_switchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_caso"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloque_caso([NotNull] gramaticaParser.Bloque_casoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_caso"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloque_caso([NotNull] gramaticaParser.Bloque_casoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bloqueDefault</c>
	/// labeled alternative in <see cref="gramaticaParser.bloque_default"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloqueDefault([NotNull] gramaticaParser.BloqueDefaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bloqueDefault</c>
	/// labeled alternative in <see cref="gramaticaParser.bloque_default"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloqueDefault([NotNull] gramaticaParser.BloqueDefaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentecia_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentecia_return([NotNull] gramaticaParser.Sentecia_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentecia_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentecia_return([NotNull] gramaticaParser.Sentecia_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentencia_break([NotNull] gramaticaParser.Sentencia_breakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentencia_break([NotNull] gramaticaParser.Sentencia_breakContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentencia_continue([NotNull] gramaticaParser.Sentencia_continueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentencia_continue([NotNull] gramaticaParser.Sentencia_continueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>llamadaFuncionCompleta</c>
	/// labeled alternative in <see cref="gramaticaParser.llamada_funcion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLlamadaFuncionCompleta([NotNull] gramaticaParser.LlamadaFuncionCompletaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>llamadaFuncionCompleta</c>
	/// labeled alternative in <see cref="gramaticaParser.llamada_funcion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLlamadaFuncionCompleta([NotNull] gramaticaParser.LlamadaFuncionCompletaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionPrintln</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionPrintln([NotNull] gramaticaParser.FuncionPrintlnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionPrintln</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionPrintln([NotNull] gramaticaParser.FuncionPrintlnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionAtoi</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionAtoi([NotNull] gramaticaParser.FuncionAtoiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionAtoi</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionAtoi([NotNull] gramaticaParser.FuncionAtoiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionTypeOf</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionTypeOf([NotNull] gramaticaParser.FuncionTypeOfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionTypeOf</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionTypeOf([NotNull] gramaticaParser.FuncionTypeOfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionSlicesIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionSlicesIndex([NotNull] gramaticaParser.FuncionSlicesIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionSlicesIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionSlicesIndex([NotNull] gramaticaParser.FuncionSlicesIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionStringsJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionStringsJoin([NotNull] gramaticaParser.FuncionStringsJoinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionStringsJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionStringsJoin([NotNull] gramaticaParser.FuncionStringsJoinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncionAppend([NotNull] gramaticaParser.FuncionAppendContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncionAppend([NotNull] gramaticaParser.FuncionAppendContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>listaArgumentos</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListaArgumentos([NotNull] gramaticaParser.ListaArgumentosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listaArgumentos</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListaArgumentos([NotNull] gramaticaParser.ListaArgumentosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>listaParametros</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListaParametros([NotNull] gramaticaParser.ListaParametrosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listaParametros</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListaParametros([NotNull] gramaticaParser.ListaParametrosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.parametro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametro([NotNull] gramaticaParser.ParametroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.parametro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametro([NotNull] gramaticaParser.ParametroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.declaracionSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracionSlice([NotNull] gramaticaParser.DeclaracionSliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.declaracionSlice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracionSlice([NotNull] gramaticaParser.DeclaracionSliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.lista_slice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLista_slice([NotNull] gramaticaParser.Lista_sliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.lista_slice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLista_slice([NotNull] gramaticaParser.Lista_sliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.slice_tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSlice_tipo([NotNull] gramaticaParser.Slice_tipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.slice_tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSlice_tipo([NotNull] gramaticaParser.Slice_tipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionFalse</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionFalse([NotNull] gramaticaParser.ExpresionFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionFalse</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionFalse([NotNull] gramaticaParser.ExpresionFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionAccesoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionAccesoSlice([NotNull] gramaticaParser.ExpresionAccesoSliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionAccesoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionAccesoSlice([NotNull] gramaticaParser.ExpresionAccesoSliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionLogica</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionLogica([NotNull] gramaticaParser.ExpresionLogicaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionLogica</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionLogica([NotNull] gramaticaParser.ExpresionLogicaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionParentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionParentesis([NotNull] gramaticaParser.ExpresionParentesisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionParentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionParentesis([NotNull] gramaticaParser.ExpresionParentesisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresion_slice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresion_slice([NotNull] gramaticaParser.Expresion_sliceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresion_slice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresion_slice([NotNull] gramaticaParser.Expresion_sliceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionInt</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionInt([NotNull] gramaticaParser.ExpresionIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionInt</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionInt([NotNull] gramaticaParser.ExpresionIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionIgualdad</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionIgualdad([NotNull] gramaticaParser.ExpresionIgualdadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionIgualdad</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionIgualdad([NotNull] gramaticaParser.ExpresionIgualdadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionRune</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionRune([NotNull] gramaticaParser.ExpresionRuneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionRune</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionRune([NotNull] gramaticaParser.ExpresionRuneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionSumaResta</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionSumaResta([NotNull] gramaticaParser.ExpresionSumaRestaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionSumaResta</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionSumaResta([NotNull] gramaticaParser.ExpresionSumaRestaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionFloat</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionFloat([NotNull] gramaticaParser.ExpresionFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionFloat</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionFloat([NotNull] gramaticaParser.ExpresionFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionRelacional</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionRelacional([NotNull] gramaticaParser.ExpresionRelacionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionRelacional</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionRelacional([NotNull] gramaticaParser.ExpresionRelacionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionNegacion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionNegacion([NotNull] gramaticaParser.ExpresionNegacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionNegacion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionNegacion([NotNull] gramaticaParser.ExpresionNegacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionLlamadafuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionLlamadafuncion([NotNull] gramaticaParser.ExpresionLlamadafuncionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionLlamadafuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionLlamadafuncion([NotNull] gramaticaParser.ExpresionLlamadafuncionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionMultiDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionMultiDiv([NotNull] gramaticaParser.ExpresionMultiDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionMultiDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionMultiDiv([NotNull] gramaticaParser.ExpresionMultiDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionIdentificador</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionIdentificador([NotNull] gramaticaParser.ExpresionIdentificadorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionIdentificador</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionIdentificador([NotNull] gramaticaParser.ExpresionIdentificadorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionCadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionCadena([NotNull] gramaticaParser.ExpresionCadenaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionCadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionCadena([NotNull] gramaticaParser.ExpresionCadenaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionTrue</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresionTrue([NotNull] gramaticaParser.ExpresionTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionTrue</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresionTrue([NotNull] gramaticaParser.ExpresionTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] gramaticaParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] gramaticaParser.TipoContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
