//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IgramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] gramaticaParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] gramaticaParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.lista_declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLista_declaracion([NotNull] gramaticaParser.Lista_declaracionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.lista_declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLista_declaracion([NotNull] gramaticaParser.Lista_declaracionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>declaracionVariable</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracionVariable([NotNull] gramaticaParser.DeclaracionVariableContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>declaracionVariable</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracionVariable([NotNull] gramaticaParser.DeclaracionVariableContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>declaracionFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracionFuncion([NotNull] gramaticaParser.DeclaracionFuncionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>declaracionFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracionFuncion([NotNull] gramaticaParser.DeclaracionFuncionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.lista_instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLista_instrucciones([NotNull] gramaticaParser.Lista_instruccionesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.lista_instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLista_instrucciones([NotNull] gramaticaParser.Lista_instruccionesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaAsignacion([NotNull] gramaticaParser.SentenciaAsignacionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaAsignacion([NotNull] gramaticaParser.SentenciaAsignacionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaIf</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaIf([NotNull] gramaticaParser.SentenciaIfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaIf</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaIf([NotNull] gramaticaParser.SentenciaIfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaFor</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaFor([NotNull] gramaticaParser.SentenciaForContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaFor</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaFor([NotNull] gramaticaParser.SentenciaForContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaSwitch</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaSwitch([NotNull] gramaticaParser.SentenciaSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaSwitch</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaSwitch([NotNull] gramaticaParser.SentenciaSwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaReturn</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaReturn([NotNull] gramaticaParser.SentenciaReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaReturn</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaReturn([NotNull] gramaticaParser.SentenciaReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>llamadaFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLlamadaFuncion([NotNull] gramaticaParser.LlamadaFuncionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>llamadaFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLlamadaFuncion([NotNull] gramaticaParser.LlamadaFuncionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaContinue</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaContinue([NotNull] gramaticaParser.SentenciaContinueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaContinue</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaContinue([NotNull] gramaticaParser.SentenciaContinueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaBrea</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaBrea([NotNull] gramaticaParser.SentenciaBreaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaBrea</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaBrea([NotNull] gramaticaParser.SentenciaBreaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>senteciaAux</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSenteciaAux([NotNull] gramaticaParser.SenteciaAuxContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>senteciaAux</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSenteciaAux([NotNull] gramaticaParser.SenteciaAuxContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsigacionconValor</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaAsigacionconValor([NotNull] gramaticaParser.SentenciaAsigacionconValorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsigacionconValor</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaAsigacionconValor([NotNull] gramaticaParser.SentenciaAsigacionconValorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsignacionComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaAsignacionComun([NotNull] gramaticaParser.SentenciaAsignacionComunContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsignacionComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaAsignacionComun([NotNull] gramaticaParser.SentenciaAsignacionComunContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaIncremento</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaIncremento([NotNull] gramaticaParser.SentenciaIncrementoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaIncremento</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaIncremento([NotNull] gramaticaParser.SentenciaIncrementoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaAsignacionSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaAsignacionSlice([NotNull] gramaticaParser.SentenciaAsignacionSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaAsignacionSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaAsignacionSlice([NotNull] gramaticaParser.SentenciaAsignacionSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentencia_if([NotNull] gramaticaParser.Sentencia_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentencia_if([NotNull] gramaticaParser.Sentencia_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloque_if([NotNull] gramaticaParser.Bloque_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloque_if([NotNull] gramaticaParser.Bloque_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloque_if_else([NotNull] gramaticaParser.Bloque_if_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloque_if_else([NotNull] gramaticaParser.Bloque_if_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloque_else([NotNull] gramaticaParser.Bloque_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloque_else([NotNull] gramaticaParser.Bloque_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaForComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaForComun([NotNull] gramaticaParser.SentenciaForComunContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaForComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaForComun([NotNull] gramaticaParser.SentenciaForComunContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sentenciaForEstiloGo</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentenciaForEstiloGo([NotNull] gramaticaParser.SentenciaForEstiloGoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sentenciaForEstiloGo</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentenciaForEstiloGo([NotNull] gramaticaParser.SentenciaForEstiloGoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentencia_switch([NotNull] gramaticaParser.Sentencia_switchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentencia_switch([NotNull] gramaticaParser.Sentencia_switchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque_caso"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloque_caso([NotNull] gramaticaParser.Bloque_casoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque_caso"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloque_caso([NotNull] gramaticaParser.Bloque_casoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bloqueDefault</c>
	/// labeled alternative in <see cref="gramaticaParser.bloque_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloqueDefault([NotNull] gramaticaParser.BloqueDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bloqueDefault</c>
	/// labeled alternative in <see cref="gramaticaParser.bloque_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloqueDefault([NotNull] gramaticaParser.BloqueDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentecia_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentecia_return([NotNull] gramaticaParser.Sentecia_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentecia_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentecia_return([NotNull] gramaticaParser.Sentecia_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentencia_break([NotNull] gramaticaParser.Sentencia_breakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentencia_break([NotNull] gramaticaParser.Sentencia_breakContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sentencia_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentencia_continue([NotNull] gramaticaParser.Sentencia_continueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sentencia_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentencia_continue([NotNull] gramaticaParser.Sentencia_continueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>llamadaFuncionCompleta</c>
	/// labeled alternative in <see cref="gramaticaParser.llamada_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLlamadaFuncionCompleta([NotNull] gramaticaParser.LlamadaFuncionCompletaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>llamadaFuncionCompleta</c>
	/// labeled alternative in <see cref="gramaticaParser.llamada_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLlamadaFuncionCompleta([NotNull] gramaticaParser.LlamadaFuncionCompletaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionPrintln</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionPrintln([NotNull] gramaticaParser.FuncionPrintlnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionPrintln</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionPrintln([NotNull] gramaticaParser.FuncionPrintlnContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionAtoi</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionAtoi([NotNull] gramaticaParser.FuncionAtoiContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionAtoi</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionAtoi([NotNull] gramaticaParser.FuncionAtoiContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionTypeOf</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionTypeOf([NotNull] gramaticaParser.FuncionTypeOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionTypeOf</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionTypeOf([NotNull] gramaticaParser.FuncionTypeOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionSlicesIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionSlicesIndex([NotNull] gramaticaParser.FuncionSlicesIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionSlicesIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionSlicesIndex([NotNull] gramaticaParser.FuncionSlicesIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionStringsJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionStringsJoin([NotNull] gramaticaParser.FuncionStringsJoinContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionStringsJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionStringsJoin([NotNull] gramaticaParser.FuncionStringsJoinContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcionAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncionAppend([NotNull] gramaticaParser.FuncionAppendContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcionAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncionAppend([NotNull] gramaticaParser.FuncionAppendContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>listaArgumentos</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListaArgumentos([NotNull] gramaticaParser.ListaArgumentosContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listaArgumentos</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListaArgumentos([NotNull] gramaticaParser.ListaArgumentosContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>listaParametros</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListaParametros([NotNull] gramaticaParser.ListaParametrosContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listaParametros</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListaParametros([NotNull] gramaticaParser.ListaParametrosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.parametro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametro([NotNull] gramaticaParser.ParametroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.parametro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametro([NotNull] gramaticaParser.ParametroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.declaracionSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracionSlice([NotNull] gramaticaParser.DeclaracionSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.declaracionSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracionSlice([NotNull] gramaticaParser.DeclaracionSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.lista_slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLista_slice([NotNull] gramaticaParser.Lista_sliceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.lista_slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLista_slice([NotNull] gramaticaParser.Lista_sliceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.slice_tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlice_tipo([NotNull] gramaticaParser.Slice_tipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.slice_tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlice_tipo([NotNull] gramaticaParser.Slice_tipoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionFalse</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionFalse([NotNull] gramaticaParser.ExpresionFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionFalse</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionFalse([NotNull] gramaticaParser.ExpresionFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionAccesoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionAccesoSlice([NotNull] gramaticaParser.ExpresionAccesoSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionAccesoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionAccesoSlice([NotNull] gramaticaParser.ExpresionAccesoSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionLogica</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionLogica([NotNull] gramaticaParser.ExpresionLogicaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionLogica</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionLogica([NotNull] gramaticaParser.ExpresionLogicaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionParentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionParentesis([NotNull] gramaticaParser.ExpresionParentesisContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionParentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionParentesis([NotNull] gramaticaParser.ExpresionParentesisContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresion_slice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresion_slice([NotNull] gramaticaParser.Expresion_sliceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresion_slice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresion_slice([NotNull] gramaticaParser.Expresion_sliceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionInt</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionInt([NotNull] gramaticaParser.ExpresionIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionInt</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionInt([NotNull] gramaticaParser.ExpresionIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionIgualdad</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionIgualdad([NotNull] gramaticaParser.ExpresionIgualdadContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionIgualdad</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionIgualdad([NotNull] gramaticaParser.ExpresionIgualdadContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionRune</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionRune([NotNull] gramaticaParser.ExpresionRuneContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionRune</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionRune([NotNull] gramaticaParser.ExpresionRuneContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionSumaResta</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionSumaResta([NotNull] gramaticaParser.ExpresionSumaRestaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionSumaResta</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionSumaResta([NotNull] gramaticaParser.ExpresionSumaRestaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionFloat</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionFloat([NotNull] gramaticaParser.ExpresionFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionFloat</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionFloat([NotNull] gramaticaParser.ExpresionFloatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionRelacional</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionRelacional([NotNull] gramaticaParser.ExpresionRelacionalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionRelacional</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionRelacional([NotNull] gramaticaParser.ExpresionRelacionalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionNegacion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionNegacion([NotNull] gramaticaParser.ExpresionNegacionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionNegacion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionNegacion([NotNull] gramaticaParser.ExpresionNegacionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionLlamadafuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionLlamadafuncion([NotNull] gramaticaParser.ExpresionLlamadafuncionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionLlamadafuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionLlamadafuncion([NotNull] gramaticaParser.ExpresionLlamadafuncionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionMultiDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionMultiDiv([NotNull] gramaticaParser.ExpresionMultiDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionMultiDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionMultiDiv([NotNull] gramaticaParser.ExpresionMultiDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionIdentificador</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionIdentificador([NotNull] gramaticaParser.ExpresionIdentificadorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionIdentificador</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionIdentificador([NotNull] gramaticaParser.ExpresionIdentificadorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionCadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionCadena([NotNull] gramaticaParser.ExpresionCadenaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionCadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionCadena([NotNull] gramaticaParser.ExpresionCadenaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expresionTrue</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresionTrue([NotNull] gramaticaParser.ExpresionTrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expresionTrue</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresionTrue([NotNull] gramaticaParser.ExpresionTrueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] gramaticaParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] gramaticaParser.TipoContext context);
}
