//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="gramaticaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IgramaticaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] gramaticaParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.lista_declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_declaracion([NotNull] gramaticaParser.Lista_declaracionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionVariable</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionVariable([NotNull] gramaticaParser.DeclaracionVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.declaracion_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionFuncion([NotNull] gramaticaParser.DeclaracionFuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.lista_instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_instrucciones([NotNull] gramaticaParser.Lista_instruccionesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaAsignacion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaAsignacion([NotNull] gramaticaParser.SentenciaAsignacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaIf</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaIf([NotNull] gramaticaParser.SentenciaIfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaFor</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaFor([NotNull] gramaticaParser.SentenciaForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaSwitch</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaSwitch([NotNull] gramaticaParser.SentenciaSwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaReturn</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaReturn([NotNull] gramaticaParser.SentenciaReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>llamadaFuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadaFuncion([NotNull] gramaticaParser.LlamadaFuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaContinue</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaContinue([NotNull] gramaticaParser.SentenciaContinueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaBrea</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaBrea([NotNull] gramaticaParser.SentenciaBreaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>senteciaAux</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenteciaAux([NotNull] gramaticaParser.SenteciaAuxContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaAsigacionconValor</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaAsigacionconValor([NotNull] gramaticaParser.SentenciaAsigacionconValorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaAsignacionComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaAsignacionComun([NotNull] gramaticaParser.SentenciaAsignacionComunContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaIncremento</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaIncremento([NotNull] gramaticaParser.SentenciaIncrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaAsignacionSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaAsignacionSlice([NotNull] gramaticaParser.SentenciaAsignacionSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.sentencia_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencia_if([NotNull] gramaticaParser.Sentencia_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.bloque_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque_if([NotNull] gramaticaParser.Bloque_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.bloque_if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque_if_else([NotNull] gramaticaParser.Bloque_if_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.bloque_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque_else([NotNull] gramaticaParser.Bloque_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaForComun</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaForComun([NotNull] gramaticaParser.SentenciaForComunContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sentenciaForEstiloGo</c>
	/// labeled alternative in <see cref="gramaticaParser.sentencia_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaForEstiloGo([NotNull] gramaticaParser.SentenciaForEstiloGoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.sentencia_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencia_switch([NotNull] gramaticaParser.Sentencia_switchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.bloque_caso"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque_caso([NotNull] gramaticaParser.Bloque_casoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bloqueDefault</c>
	/// labeled alternative in <see cref="gramaticaParser.bloque_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloqueDefault([NotNull] gramaticaParser.BloqueDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.sentecia_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentecia_return([NotNull] gramaticaParser.Sentecia_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.sentencia_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencia_break([NotNull] gramaticaParser.Sentencia_breakContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.sentencia_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencia_continue([NotNull] gramaticaParser.Sentencia_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>llamadaFuncionCompleta</c>
	/// labeled alternative in <see cref="gramaticaParser.llamada_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadaFuncionCompleta([NotNull] gramaticaParser.LlamadaFuncionCompletaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionPrintln</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionPrintln([NotNull] gramaticaParser.FuncionPrintlnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionAtoi</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionAtoi([NotNull] gramaticaParser.FuncionAtoiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionTypeOf</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionTypeOf([NotNull] gramaticaParser.FuncionTypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionSlicesIndex</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionSlicesIndex([NotNull] gramaticaParser.FuncionSlicesIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionStringsJoin</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionStringsJoin([NotNull] gramaticaParser.FuncionStringsJoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionAppend</c>
	/// labeled alternative in <see cref="gramaticaParser.funcion_embedida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionAppend([NotNull] gramaticaParser.FuncionAppendContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listaArgumentos</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaArgumentos([NotNull] gramaticaParser.ListaArgumentosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listaParametros</c>
	/// labeled alternative in <see cref="gramaticaParser.lista_parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaParametros([NotNull] gramaticaParser.ListaParametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.parametro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametro([NotNull] gramaticaParser.ParametroContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.declaracionSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionSlice([NotNull] gramaticaParser.DeclaracionSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.lista_slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_slice([NotNull] gramaticaParser.Lista_sliceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.slice_tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlice_tipo([NotNull] gramaticaParser.Slice_tipoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionFalse</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionFalse([NotNull] gramaticaParser.ExpresionFalseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionAccesoSlice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionAccesoSlice([NotNull] gramaticaParser.ExpresionAccesoSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionLogica</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionLogica([NotNull] gramaticaParser.ExpresionLogicaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionParentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionParentesis([NotNull] gramaticaParser.ExpresionParentesisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresion_slice</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresion_slice([NotNull] gramaticaParser.Expresion_sliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionInt</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionInt([NotNull] gramaticaParser.ExpresionIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionIgualdad</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionIgualdad([NotNull] gramaticaParser.ExpresionIgualdadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionRune</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionRune([NotNull] gramaticaParser.ExpresionRuneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionSumaResta</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionSumaResta([NotNull] gramaticaParser.ExpresionSumaRestaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionFloat</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionFloat([NotNull] gramaticaParser.ExpresionFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionRelacional</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionRelacional([NotNull] gramaticaParser.ExpresionRelacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionNegacion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionNegacion([NotNull] gramaticaParser.ExpresionNegacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionLlamadafuncion</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionLlamadafuncion([NotNull] gramaticaParser.ExpresionLlamadafuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionMultiDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionMultiDiv([NotNull] gramaticaParser.ExpresionMultiDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionIdentificador</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionIdentificador([NotNull] gramaticaParser.ExpresionIdentificadorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionCadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionCadena([NotNull] gramaticaParser.ExpresionCadenaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expresionTrue</c>
	/// labeled alternative in <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionTrue([NotNull] gramaticaParser.ExpresionTrueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] gramaticaParser.TipoContext context);
}
